apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-7ums
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/e2e-demos-wsrj-tenant/rhtap-demo-app/hacbs-test-project-7ums@sha256:9f8a02b7bff11117dc76646c7d6b9c98ce2562bfd05be245771dc949e35f0d92
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
