apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-7ums
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-7ums
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-7ums
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-7ums
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-7ums
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/e2e-demos-wsrj-tenant/rhtap-demo-app/hacbs-test-project-7ums@sha256:9f8a02b7bff11117dc76646c7d6b9c98ce2562bfd05be245771dc949e35f0d92
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
